extends Node

@warning_ignore("unused_signal")
signal new_game
@warning_ignore("unused_signal")
signal card_added_to_labyrinth(card: Card)
@warning_ignore("unused_signal")
signal card_added_to_discard(card: Card, draw_card: bool)
@warning_ignore("unused_signal")
signal card_added_to_limbo(card: Card)
@warning_ignore("unused_signal")
signal card_removed_from_limbo(card: Card)
@warning_ignore("unused_signal")
signal card_return_to_hand(card: Card)
@warning_ignore("unused_signal")
signal door_discarded(color: CardManager.CARD_COLOR)
@warning_ignore("unused_signal")
signal nightmare_button_selected(type: Constants.NIGHTMARE_DISCARD, selected: bool)
@warning_ignore("unused_signal")
signal nightmare_action_selected(type: Constants.NIGHTMARE_DISCARD)
@warning_ignore("unused_signal")
signal touch_event(object: Variant)
@warning_ignore("unused_signal")
signal key_open_door_selected(type: Constants.KEY_OPEN_DOOR, key: Card, door: Card)
@warning_ignore("unused_signal")
signal swap_prophecy_cards(card1: ProphecyCard, card2: ProphecyCard)
@warning_ignore("unused_signal")
signal prophecy_cards_reset_position(card: ProphecyCard)
@warning_ignore("unused_signal")
signal deck_outline_enabled(enabled: bool)
